### ISSUE TITLE
Example of adaptive weightFunction?

### ISSUE THREAD

**Issue by alecjacobson** [cemyuksel/cyCodeBase#10]
I'm loving the blue noise sampler on surfaces in 3D. In the default "uniform importance" mode it's working great! Thanks for sharing this great implementation of a great algorithm.

I'm struggling to get the weightFunction working correctly for adaptive importance. Wondering if you could give some pointers?

For example, I'm trying to create sampling of this rectangle with more samples toward the center and decreasing "smoothly" toward the edges. 

I tried using this as my weightFunction:

```
  const auto weight = 
    [d_min, alpha](
    PointType const & p0, 
    PointType const & p1, 
    FType d2, 
    FType d_max)
  {
    FType d = cy::Sqrt(d2)*(3.0-2.0*(1.0-p0.Length()));
    return std::pow( FType(1) - d/d_max, alpha );
  };
```

But the result is clumpy:

<img width="1213" alt="image" src="https://user-images.githubusercontent.com/2241689/71611954-faa70900-2b6a-11ea-8a0c-3f2c9e57d403.png">

**Comment by cemyuksel** [comment]
Your weight function seems fine to me. It might be related to the bounds of p0.Length(). It should not be greater than 1. You may need to scale it accordingly.
