### ISSUE TITLE
Bug in GetMaxPoissonDiskRadius in Weighted Sample Elimination

### ISSUE THREAD

**Issue by graphitemaster** [cemyuksel/cyCodeBase#17]
When omitting the domain size to `GetMaxPoissonDiskRadius` this function computes the area or N-dimensional volume of the box, except the loop which goes over all the dimensions fails to index the bounds array and always uses the first axis, as can be seen here
<https://github.com/cemyuksel/cyCodeBase/blob/master/cySampleElim.h#L279>

Trivial patch provided
```diff
- for ( int d=1; d<DIMENSIONS; d++ ) domainSize *= boundsMax[0] - boundsMin[0];
+ for ( int d=1; d<DIMENSIONS; d++ ) domainSize *= boundsMax[d] - boundsMin[d];
```

**Comment by cemyuksel** [comment]
Nice catch! This is fixed in the latest update.
