### ISSUE TITLE
#include_next <Intrin.h> 'Intrin.h' file not found

### ISSUE THREAD

**Issue by ruiwng** [cemyuksel/cyCodeBase#18]
Hello,
I came across an error when using cyCodeBase with clang as compiler on MacOS. 
```
In file included from ./cyVector.h:39:
In file included from ./cyCore.h:56:
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/13.0.0/include/intrin.h:12:15: fatal error: 'Intrin.h' file not found
#include_next <Intrin.h>
              ^~~~~~~~~~
1 error generated.
```
I googled it and found a solution [here](https://bugs.llvm.org/show_bug.cgi?id=23147). intrin.h is only supposed to be used on Windows platform. including <x86intrin.h> instead of <intrin.h> in cyCore.h file will solve this problem, I have tried it.

**Comment by cemyuksel** [comment]
Thanks for letting me know. This is fixed in the latest update using the `<immintrin.h>` header instead.

**Comment by xarthurx** [comment]
The code base cannot be compiled on macOS (arm64).

```bash
  In file included from /Users/runner/work/BeingAliveLanguageGH/BeingAliveLanguageGH/GeoSharPlusCPP/../external/cyCodeBase/cyCore.h:56:
  Error: /Applications/Xcode_15.4.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/15.0.0/include/immintrin.h:14:2: error: "This header is only meant to be used on x86 and x64 architecture"
  #error "This header is only meant to be used on x86 and x64 architecture"
```

Does it have a solution for the `arm64` platform?

I saw in the code:
```cpp
#if !defined(CY_NO_INTRIN_H) && !defined(CY_NO_EMMINTRIN_H) && !defined(CY_NO_IMMINTRIN_H)
# include <immintrin.h>
#endif
```

May I ask how to avoid it while making the code base still working?
