### ISSUE TITLE
How could I generate the hair model files?

### ISSUE THREAD

**Issue by ZhengzhongSun** [cemyuksel/cyCodeBase#4]
I have modeled the hair in maya. Is there a script to export it in the format of cyhairfile?
Thank you very much!

**Comment by cemyuksel** [comment]
There is no script that I know of. You may have to write your own script.

**Comment by povmaniaco** [comment]
HI.. You have here an script example writed in python...
https://github.com/TheBounty/Blender-Exporter/blob/291b002823a8682ccc283877f2a80642fd08d779/io/tby_object.py#L683

also based on this code..

https://bitbucket.org/luxrender/luxblend25/src/89a9fe4f754cf7201a871ecd604182ceb6c8c57e/src/luxrender/export/geometry.py?at=default&fileviewer=file-view-default#geometry.py-1110
