### ISSUE TITLE
cyPi undefined

### ISSUE THREAD

**Issue by alecjacobson** [cemyuksel/cyCodeBase#9]
https://github.com/cemyuksel/cyCodeBase/blob/91899441de621dc714376762404e48932b50bf3d/cySampleElim.h#L289

    ./cySampleElim.h:289:34: error: use of undeclared identifier 'cyPi'

I'm guessing this function returns pi=3.14... in the correct type.

**Comment by cemyuksel** [comment]
Indeed. Thanks for letting me know. I've noticed a few other old math function calls and fixed them all.
